# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  cosmic_builder:
    target: ":cosmic_builder"
    import: "package:cosmic/cosmic_lib.dart"
    builder_factories: ["cosmicBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
    auto_apply: dependents