name: cosmic
description: Simple work with REST JSON API
version: 1.1.1
homepage: https://github.com/IdanAizikNissim/Cosmic
author: Idan Aizik-Nissim <idan.aizik.nissim@gmail.com>

environment:
  sdk: '>=2.0.0'

dependencies:
  meta: "^1.1.2"
  http: "^0.11.3+14"
  args: "^1.4.1"
  path: "^1.4.2"
  dart_style: "^1.0.7"
  build: ^1.0.2
  source_gen: ^0.9.3

dev_dependencies:
  build_runner: any
  build_test: any
