name: cosmic
description: Simple work with REST JSON API
version: 0.0.1
homepage: https://gitlab.com/idan-aizik-nissim/dart-cosmic
author: Idan Aizik-Nissim <idan.aizik.nissim@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "^0.11.3+14"
  jsonx: "^2.0.2"
  args: '>=0.12.1 <0.14.0'
  path: "^1.4.2"
  dart_style: "^1.0.7"

dev_dependencies:
#  test: ^0.12.0
